spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aircraftcarrier?allowMultiQueries=true&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 12345678
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  # 苞米豆依赖spring配置
  redis:
    # 云版本
#    cluster:
#      nodes:
#        - 82.157.100.48:6381
#        - 82.157.100.48:6382
#        - 82.157.100.48:6383
    password: 123123
    # 单机版
    host: 82.157.100.48
    port: 6379

knife4j:
  production: false # 是否开启屏蔽文档资源
  enable: true
  setting:
    enableDebug: true

easy-es:
  enable: false # 默认为true,若为false时,则认为不启用本框架
  address: 82.157.100.48:9200
#  username: elastic #es用户名,若无则删去此行配置
#  password: WG7WVmuNMtM4GwNYkyWH #es密码,若无则删去此行配置

rocketmq:
  topic: my_rocketmq_topic
  name-server: 82.157.100.48:9876
  producer:
    group: my-group
    send-message-timeout: 30000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-async-failed: 0
    retry-next-server: true
    retry-times-when-send-failed: 2


