server:
  port: 8383
  shutdown: graceful #开启优雅停机
  netty:
    connection-timeout: 5000ms
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/javascript

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s #设置缓冲时间 默认30s
  profiles:
    active: dev,extend
  messages:
    encoding: UTF-8
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.aircraftcarrier.marketing.store.infrastructure.repository.dataobject
  typeEnumsPackage:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
