package com.aircraftcarrier.marketing.store.api.model;

import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Only returned in the event of an error condition.
 */
@ApiModel(description = "Only returned in the event of an error condition.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-03T18:13:45.340+01:00[Europe/London]")
public class Error {
    public static final String SERIALIZED_NAME_SOURCE = "source";
    @JSONField(name = SERIALIZED_NAME_SOURCE)
    private String source;

    public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
    @JSONField(name = SERIALIZED_NAME_ERROR_CODE)
    private String errorCode;

    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @JSONField(name = SERIALIZED_NAME_DESCRIPTION)
    private String description;

    public static final String SERIALIZED_NAME_REASON_CODE = "reasonCode";
    @JSONField(name = SERIALIZED_NAME_REASON_CODE)
    private String reasonCode;

    public static final String SERIALIZED_NAME_RECOVERABLE = "recoverable";
    @JSONField(name = SERIALIZED_NAME_RECOVERABLE)
    private Boolean recoverable;


    public Error source(String source) {
        this.source = source;
        return this;
    }

    /**
     * An element used to indicate the source of the issue causing this error. Must be one of  * &#39;MDES&#39;  * &#39;INPUT&#39;
     *
     * @return source
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "An element used to indicate the source of the issue causing this error. Must be one of  * 'MDES'  * 'INPUT' ")
    public String getSource() {
        return source;
    }


    public void setSource(String source) {
        this.source = source;
    }


    public Error errorCode(String errorCode) {
        this.errorCode = errorCode;
        return this;
    }

    /**
     * An error code generated by the gateway if the error occurs before reaching the MDES application. maxLength: 100
     *
     * @return errorCode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "An error code generated by the gateway if the error occurs before reaching the MDES application. maxLength: 100 ")
    public String getErrorCode() {
        return errorCode;
    }


    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }


    public Error description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Description of the reason the operation failed. See API Response Errors
     *
     * @return description
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Description of the reason the operation failed. See API Response Errors ")
    public String getDescription() {
        return description;
    }


    public void setDescription(String description) {
        this.description = description;
    }


    public Error reasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
        return this;
    }

    /**
     * A reason code for the error that has occurred.
     *
     * @return reasonCode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "A reason code for the error that has occurred. ")
    public String getReasonCode() {
        return reasonCode;
    }


    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }


    public Error recoverable(Boolean recoverable) {
        this.recoverable = recoverable;
        return this;
    }

    /**
     * Generated by the gateway to indicate if the request could presented again for processing. Either \&quot;TRUE\&quot; or \&quot;FALSE\&quot;
     *
     * @return recoverable
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "true", value = "Generated by the gateway to indicate if the request could presented again for processing. Either \"TRUE\" or \"FALSE\" ")
    public Boolean getRecoverable() {
        return recoverable;
    }


    public void setRecoverable(Boolean recoverable) {
        this.recoverable = recoverable;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error error = (Error) o;
        return Objects.equals(this.source, error.source) &&
                Objects.equals(this.errorCode, error.errorCode) &&
                Objects.equals(this.description, error.description) &&
                Objects.equals(this.reasonCode, error.reasonCode) &&
                Objects.equals(this.recoverable, error.recoverable);
    }

    @Override
    public int hashCode() {
        return Objects.hash(source, errorCode, description, reasonCode, recoverable);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Error {\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
        sb.append("    recoverable: ").append(toIndentedString(recoverable)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

